[package]
name = "fuzzyserve"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.9"
actix-web = "4.12.1"
clap = { version = "4.5.54", features = ["derive"] }
ctrlc = "3.5.1"
fuzzy-matcher = "0.3.7"
notify = "8.2.0"
parking_lot = "0.12.5"
percent-encoding = "2.3.2"
urlencoding = "2"
v_htmlescape = "0.15.8"
walkdir = "2.5.0"
